debug:
  enable: false
  output: BOTH
  level: FINE
stats: true
language: en
onlyPVPinArena: false
safeadmin: true
spawnOffset:
  x: 0.5
  y: 0.5
  z: 0.5
wandItem: STICK
whitelist:
- ungod
whitelist_wildcard: false
use_shortcuts: false
only_shortcuts: false
shortcut_shuffle: false
allow_ungrouped: false
consoleoffduty: false
update:
  plugin: announce
  modules: announce
globalPrefix: 'PVP Arena'
signHeaders:
  - '[arena]'
  - '[PVP Arena]'